version: "3.8"

services:
  api:
    container_name: api
    build:
      context: ./server
      dockerfile: Dockerfile.dev # on move to prod, update this
    volumes:
      - /api/node_modules
      - ./server:/api
    ports:
      - "5000:5000"
    networks:
      - app
    restart: unless-stopped
  app:
    container_name: app
    build:
      context: ./client
      dockerfile: Dockerfile.dev # on move to prod, update this
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "3000:3000"
    networks:
      - app
    restart: unless-stopped
networks:
  app:
    driver: bridge
