@limit = 20
@offset = 0

### GET books
# @name books
GET {{baseUrl}}/books/latest
?limit={{limit}}
&offset={{offset}}
Content-Type: {{contentType}}

### POST books
# @name books
POST {{baseUrl}}/books
Content-Type: {{contentType}}

{
    "name": "Testikirja"
}
